//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.11 at 03:44:07 PM CET 
//


package org.kaleta.lolstats.backend.entity;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "lolApi",
    "seasons"
})
@XmlRootElement(name = "config")
public class Config {
    @XmlElement(name = "lol-api", required = true)
    protected LolApi lolApi;
    @XmlElement(required = true)
    protected Seasons seasons;

    public Config(){
        lolApi = new LolApi();
        seasons = new Seasons();
    }

    /**
     * Gets the value of the lolApi property.
     * 
     * @return
     *     possible object is
     *     {@link LolApi }
     *     
     */
    public LolApi getLolApi() {
        return lolApi;
    }

    /**
     * Sets the value of the lolApi property.
     * 
     * @param value
     *     allowed object is
     *     {@link LolApi }
     *     
     */
    public void setLolApi(LolApi value) {
        this.lolApi = value;
    }

    /**
     * Gets the value of the seasons property.
     * 
     * @return
     *     possible object is
     *     {@link Seasons }
     *     
     */
    public Seasons getSeasons() {
        return seasons;
    }

    /**
     * Sets the value of the seasons property.
     * 
     * @param value
     *     allowed object is
     *     {@link Seasons }
     *     
     */
    public void setSeasons(Seasons value) {
        this.seasons = value;
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class LolApi {
        @XmlAttribute(name = "region", required = true)
        protected String region;
        @XmlAttribute(name = "nick", required = true)
        protected String nick;
        @XmlAttribute(name = "access-key", required = true)
        protected String accessKey;

        public LolApi(){
            region = "";
            nick = "";
            accessKey = "";
        }

        /**
         * Gets the value of the region property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRegion() {
            return region;
        }

        /**
         * Sets the value of the region property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRegion(String value) {
            this.region = value;
        }

        /**
         * Gets the value of the nick property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNick() {
            return nick;
        }

        /**
         * Sets the value of the nick property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNick(String value) {
            this.nick = value;
        }

        /**
         * Gets the value of the accessKey property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAccessKey() {
            return accessKey;
        }

        /**
         * Sets the value of the accessKey property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAccessKey(String value) {
            this.accessKey = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="season" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="order" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "season"
    })
    public static class Seasons {

        protected List<Season> season;

        /**
         * Gets the value of the season property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the season property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSeason().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Season }
         * 
         * 
         */
        public List<Season> getSeason() {
            if (season == null) {
                season = new ArrayList<Season>();
            }
            return this.season;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="order" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Season {
            @XmlAttribute(name = "order", required = true)
            protected String order;
            @XmlAttribute(name = "id", required = true)
            protected String id;

            public Season(){
                order = "";
                id = "";
            }

            /**
             * Gets the value of the order property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOrder() {
                return order;
            }

            /**
             * Sets the value of the order property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOrder(String value) {
                this.order = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

        }

    }

}
