//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.01 at 12:54:03 PM CET 
//


package org.kaleta.lolstats.backend.entity;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for player complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="player">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="score">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="multi">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="double" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="triple" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="quadra" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="penta" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="kills" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="deaths" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="assists" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="max-killing-spree" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="dmg">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="total" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="to-champs" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ward">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="placed" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="destroyed" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="champ" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="role" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="farm" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="gold" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fb" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="turrets" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "player", propOrder = {
    "score",
    "dmg",
    "ward"
})
public class Player {

    @XmlElement(required = true)
    protected Score score = new Score();
    @XmlElement(required = true)
    protected Dmg dmg = new Dmg();
    @XmlElement(required = true)
    protected Ward ward = new Ward();
    @XmlAttribute(name = "champ", required = true)
    protected String champ="";
    @XmlAttribute(name = "role", required = true)
    protected String role="";
    @XmlAttribute(name = "farm", required = true)
    protected String farm="";
    @XmlAttribute(name = "gold", required = true)
    protected String gold="";
    @XmlAttribute(name = "fb", required = true)
    protected String fb="";
    @XmlAttribute(name = "turrets", required = true)
    protected String turrets="";

    /**
     * Gets the value of the score property.
     * 
     * @return
     *     possible object is
     *     {@link Score }
     *     
     */
    public Score getScore() {
        return score;
    }

    /**
     * Sets the value of the score property.
     * 
     * @param value
     *     allowed object is
     *     {@link Score }
     *     
     */
    public void setScore(Score value) {
        this.score = value;
    }

    /**
     * Gets the value of the dmg property.
     * 
     * @return
     *     possible object is
     *     {@link Dmg }
     *     
     */
    public Dmg getDmg() {
        return dmg;
    }

    /**
     * Sets the value of the dmg property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dmg }
     *     
     */
    public void setDmg(Dmg value) {
        this.dmg = value;
    }

    /**
     * Gets the value of the ward property.
     * 
     * @return
     *     possible object is
     *     {@link Ward }
     *     
     */
    public Ward getWard() {
        return ward;
    }

    /**
     * Sets the value of the ward property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ward }
     *     
     */
    public void setWard(Ward value) {
        this.ward = value;
    }

    /**
     * Gets the value of the champ property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChamp() {
        return champ;
    }

    /**
     * Sets the value of the champ property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChamp(String value) {
        this.champ = value;
    }

    /**
     * Gets the value of the role property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRole() {
        return role;
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRole(String value) {
        this.role = value;
    }

    /**
     * Gets the value of the farm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFarm() {
        return farm;
    }

    /**
     * Sets the value of the farm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFarm(String value) {
        this.farm = value;
    }

    /**
     * Gets the value of the gold property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGold() {
        return gold;
    }

    /**
     * Sets the value of the gold property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGold(String value) {
        this.gold = value;
    }

    /**
     * Gets the value of the fb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFb() {
        return fb;
    }

    /**
     * Sets the value of the fb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFb(String value) {
        this.fb = value;
    }

    /**
     * Gets the value of the turrets property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTurrets() {
        return turrets;
    }

    /**
     * Sets the value of the turrets property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTurrets(String value) {
        this.turrets = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="total" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="to-champs" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Dmg {

        @XmlAttribute(name = "total", required = true)
        protected String total="";
        @XmlAttribute(name = "to-champs", required = true)
        protected String toChamps="";

        /**
         * Gets the value of the total property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTotal() {
            return total;
        }

        /**
         * Sets the value of the total property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTotal(String value) {
            this.total = value;
        }

        /**
         * Gets the value of the toChamps property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getToChamps() {
            return toChamps;
        }

        /**
         * Sets the value of the toChamps property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setToChamps(String value) {
            this.toChamps = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="multi">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="double" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="triple" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="quadra" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="penta" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="kills" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="deaths" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="assists" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="max-killing-spree" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "multi"
    })
    public static class Score {

        @XmlElement(required = true)
        protected Multi multi = new Multi();
        @XmlAttribute(name = "kills", required = true)
        protected String kills="";
        @XmlAttribute(name = "deaths", required = true)
        protected String deaths="";
        @XmlAttribute(name = "assists", required = true)
        protected String assists="";
        @XmlAttribute(name = "max-killing-spree", required = true)
        protected String maxKillingSpree="";

        /**
         * Gets the value of the multi property.
         * 
         * @return
         *     possible object is
         *     {@link Multi }
         *     
         */
        public Multi getMulti() {
            return multi;
        }

        /**
         * Sets the value of the multi property.
         * 
         * @param value
         *     allowed object is
         *     {@link Multi }
         *     
         */
        public void setMulti(Multi value) {
            this.multi = value;
        }

        /**
         * Gets the value of the kills property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getKills() {
            return kills;
        }

        /**
         * Sets the value of the kills property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setKills(String value) {
            this.kills = value;
        }

        /**
         * Gets the value of the deaths property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDeaths() {
            return deaths;
        }

        /**
         * Sets the value of the deaths property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDeaths(String value) {
            this.deaths = value;
        }

        /**
         * Gets the value of the assists property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAssists() {
            return assists;
        }

        /**
         * Sets the value of the assists property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAssists(String value) {
            this.assists = value;
        }

        /**
         * Gets the value of the maxKillingSpree property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMaxKillingSpree() {
            return maxKillingSpree;
        }

        /**
         * Sets the value of the maxKillingSpree property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMaxKillingSpree(String value) {
            this.maxKillingSpree = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="double" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="triple" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="quadra" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="penta" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Multi {

            @XmlAttribute(name = "double", required = true)
            protected String _double="";
            @XmlAttribute(name = "triple", required = true)
            protected String triple="";
            @XmlAttribute(name = "quadra", required = true)
            protected String quadra="";
            @XmlAttribute(name = "penta", required = true)
            protected String penta="";

            /**
             * Gets the value of the double property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDouble() {
                return _double;
            }

            /**
             * Sets the value of the double property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDouble(String value) {
                this._double = value;
            }

            /**
             * Gets the value of the triple property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTriple() {
                return triple;
            }

            /**
             * Sets the value of the triple property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTriple(String value) {
                this.triple = value;
            }

            /**
             * Gets the value of the quadra property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getQuadra() {
                return quadra;
            }

            /**
             * Sets the value of the quadra property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setQuadra(String value) {
                this.quadra = value;
            }

            /**
             * Gets the value of the penta property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPenta() {
                return penta;
            }

            /**
             * Sets the value of the penta property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPenta(String value) {
                this.penta = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="placed" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="destroyed" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Ward {

        @XmlAttribute(name = "placed", required = true)
        protected String placed="";
        @XmlAttribute(name = "destroyed", required = true)
        protected String destroyed="";

        /**
         * Gets the value of the placed property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlaced() {
            return placed;
        }

        /**
         * Sets the value of the placed property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlaced(String value) {
            this.placed = value;
        }

        /**
         * Gets the value of the destroyed property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDestroyed() {
            return destroyed;
        }

        /**
         * Sets the value of the destroyed property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDestroyed(String value) {
            this.destroyed = value;
        }

    }

}
