//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.01 at 12:54:03 PM CET 
//


package org.kaleta.lolstats.backend.entity;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="game" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="rank">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="tier" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="division" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="lp" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="user-team" type="{}team"/>
 *                   &lt;element name="enemy-team" type="{}team"/>
 *                   &lt;element name="user" type="{}player"/>
 *                   &lt;element name="user-mates" type="{}player" maxOccurs="4" minOccurs="4"/>
 *                   &lt;element name="opponent" type="{}player"/>
 *                   &lt;element name="opponent-mates" type="{}player" maxOccurs="4" minOccurs="4"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="number" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="date" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="length" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "game"
})
@XmlRootElement(name = "season")
public class Season {

    protected List<Game> game;
    @XmlAttribute(name = "id", required = true)
    protected String id="";
    @XmlAttribute(name = "name", required = true)
    protected String name="";

    /**
     * Gets the value of the game property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the game property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGame().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Game }
     * 
     * 
     */
    public List<Game> getGame() {
        if (game == null) {
            game = new ArrayList<Game>();
        }
        return this.game;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="rank">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="tier" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="division" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="lp" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="user-team" type="{}team"/>
     *         &lt;element name="enemy-team" type="{}team"/>
     *         &lt;element name="user" type="{}player"/>
     *         &lt;element name="user-mates" type="{}player" maxOccurs="4" minOccurs="4"/>
     *         &lt;element name="opponent" type="{}player"/>
     *         &lt;element name="opponent-mates" type="{}player" maxOccurs="4" minOccurs="4"/>
     *       &lt;/sequence>
     *       &lt;attribute name="number" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="date" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="length" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "rank",
        "userTeam",
        "enemyTeam",
        "user",
        "userMate",
        "opponent"
    })
    public static class Game {

        @XmlElement(required = true)
        protected Rank rank= new Rank();
        @XmlElement(name = "user-team", required = true)
        protected Team userTeam = new Team();
        @XmlElement(name = "enemy-team", required = true)
        protected Team enemyTeam = new Team();
        @XmlElement(required = true)
        protected Player user = new Player();
        @XmlElement(name = "user-mate", required = true)
        protected List<Player> userMate;
        @XmlElement(name = "opponent", required = true)
        protected List<Player> opponent;
        @XmlAttribute(name = "number", required = true)
        protected String number="";
        @XmlAttribute(name = "date", required = true)
        protected String date="";
        @XmlAttribute(name = "length", required = true)
        protected String length="";

        /**
         * Gets the value of the rank property.
         * 
         * @return
         *     possible object is
         *     {@link Rank }
         *     
         */
        public Rank getRank() {
            return rank;
        }

        /**
         * Sets the value of the rank property.
         * 
         * @param value
         *     allowed object is
         *     {@link Rank }
         *     
         */
        public void setRank(Rank value) {
            this.rank = value;
        }

        /**
         * Gets the value of the userTeam property.
         * 
         * @return
         *     possible object is
         *     {@link Team }
         *     
         */
        public Team getUserTeam() {
            return userTeam;
        }

        /**
         * Sets the value of the userTeam property.
         * 
         * @param value
         *     allowed object is
         *     {@link Team }
         *     
         */
        public void setUserTeam(Team value) {
            this.userTeam = value;
        }

        /**
         * Gets the value of the enemyTeam property.
         * 
         * @return
         *     possible object is
         *     {@link Team }
         *     
         */
        public Team getEnemyTeam() {
            return enemyTeam;
        }

        /**
         * Sets the value of the enemyTeam property.
         * 
         * @param value
         *     allowed object is
         *     {@link Team }
         *     
         */
        public void setEnemyTeam(Team value) {
            this.enemyTeam = value;
        }

        /**
         * Gets the value of the user property.
         * 
         * @return
         *     possible object is
         *     {@link Player }
         *     
         */
        public Player getUser() {
            return user;
        }

        /**
         * Sets the value of the user property.
         * 
         * @param value
         *     allowed object is
         *     {@link Player }
         *     
         */
        public void setUser(Player value) {
            this.user = value;
        }

        /**
         * Gets the value of the userMates property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the userMates property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUserMates().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Player }
         * 
         * 
         */
        public List<Player> getUserMate() {
            if (userMate == null) {
                userMate = new ArrayList<Player>();
            }
            return this.userMate;
        }

        /**
         * Gets the value of the opponentMates property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the opponentMates property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOpponentMates().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Player }
         * 
         * 
         */
        public List<Player> getOpponent() {
            if (opponent == null) {
                opponent = new ArrayList<Player>();
            }
            return this.opponent;
        }

        /**
         * Gets the value of the number property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNumber() {
            return number;
        }

        /**
         * Sets the value of the number property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNumber(String value) {
            this.number = value;
        }

        /**
         * Gets the value of the date property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDate() {
            return date;
        }

        /**
         * Sets the value of the date property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDate(String value) {
            this.date = value;
        }

        /**
         * Gets the value of the length property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLength() {
            return length;
        }

        /**
         * Sets the value of the length property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLength(String value) {
            this.length = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="tier" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="division" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="lp" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Rank {

            @XmlAttribute(name = "tier", required = true)
            protected String tier="";
            @XmlAttribute(name = "division", required = true)
            protected String division="";
            @XmlAttribute(name = "lp", required = true)
            protected String lp="";

            /**
             * Gets the value of the tier property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTier() {
                return tier;
            }

            /**
             * Sets the value of the tier property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTier(String value) {
                this.tier = value;
            }

            /**
             * Gets the value of the division property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDivision() {
                return division;
            }

            /**
             * Sets the value of the division property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDivision(String value) {
                this.division = value;
            }

            /**
             * Gets the value of the lp property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLp() {
                return lp;
            }

            /**
             * Sets the value of the lp property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLp(String value) {
                this.lp = value;
            }

        }

    }

}
