//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.15 at 06:22:28 PM CET 
//


package org.kaleta.lolstats.backend.entity;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="game" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="result">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="team-diff">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="kills-diff" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="farm-diff" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="gold-diff" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="total-dmg-diff" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="champ-dmg-diff" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="drake-diff" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="nashor-diff" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="herald-diff" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="turret-diff" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="inhibitor-diff" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="win" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="lp" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="length" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="first-blood" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="performance">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="dmg">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="total-dmg-absolute" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="total-dmg-team-relative" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="champ-dmg-absolute" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="champ-dmg-team-relative" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="score">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="kills-absolute" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="kills-team-relative" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="deaths-absolute" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="deaths-team-relative" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="assists-absolute" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="assists-team-relative" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="farm">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="farm-absolute" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="farm-team-relative" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="wards">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="ward-placed" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="ward-destroyed" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="multi-kills">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="double" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="triple" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="quadra" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="penta" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="first-blood" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="gold" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="turrets" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="killing-spree" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="number" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="date" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="role" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="champion" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "game"
})
@XmlRootElement(name = "season")
public class Season {

    protected List<Game> game;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "name", required = true)
    protected String name;

    /**
     * Gets the value of the game property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the game property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGame().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Game }
     * 
     * 
     */
    public List<Game> getGame() {
        if (game == null) {
            game = new ArrayList<Game>();
        }
        return this.game;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "result",
        "performance"
    })
    public static class Game {

        @XmlElement(required = true)
        protected Result result = new Result();
        @XmlElement(required = true)
        protected Performance performance = new Performance();
        @XmlAttribute(name = "number", required = true)
        protected String number = "";
        @XmlAttribute(name = "date", required = true)
        protected String date = "";
        @XmlAttribute(name = "role", required = true)
        protected String role = "";
        @XmlAttribute(name = "champion", required = true)
        protected String champion = "";

        /**
         * Gets the value of the result property.
         * 
         * @return
         *     possible object is
         *     {@link Result }
         *     
         */
        public Result getResult() {
            return result;
        }

        /**
         * Sets the value of the result property.
         * 
         * @param value
         *     allowed object is
         *     {@link Result }
         *     
         */
        public void setResult(Result value) {
            this.result = value;
        }

        /**
         * Gets the value of the performance property.
         * 
         * @return
         *     possible object is
         *     {@link Performance }
         *     
         */
        public Performance getPerformance() {
            return performance;
        }

        /**
         * Sets the value of the performance property.
         * 
         * @param value
         *     allowed object is
         *     {@link Performance }
         *     
         */
        public void setPerformance(Performance value) {
            this.performance = value;
        }

        /**
         * Gets the value of the number property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNumber() {
            return number;
        }

        /**
         * Sets the value of the number property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNumber(String value) {
            this.number = value;
        }

        /**
         * Gets the value of the date property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDate() {
            return date;
        }

        /**
         * Sets the value of the date property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDate(String value) {
            this.date = value;
        }

        /**
         * Gets the value of the role property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRole() {
            return role;
        }

        /**
         * Sets the value of the role property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRole(String value) {
            this.role = value;
        }

        /**
         * Gets the value of the champion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getChampion() {
            return champion;
        }

        /**
         * Sets the value of the champion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setChampion(String value) {
            this.champion = value;
        }

        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "dmg",
            "score",
            "farm",
            "wards",
            "multiKills"
        })
        public static class Performance {

            @XmlElement(required = true)
            protected Dmg dmg = new Dmg();
            @XmlElement(required = true)
            protected Score score = new Score();
            @XmlElement(required = true)
            protected Farm farm = new Farm();
            @XmlElement(required = true)
            protected Wards wards = new Wards();
            @XmlElement(name = "multi-kills", required = true)
            protected MultiKills multiKills = new MultiKills();
            @XmlAttribute(name = "first-blood", required = true)
            protected String firstBlood = "";
            @XmlAttribute(name = "gold", required = true)
            protected String gold = "";
            @XmlAttribute(name = "turrets", required = true)
            protected String turrets = "";
            @XmlAttribute(name = "killing-spree", required = true)
            protected String killingSpree = "";

            /**
             * Gets the value of the dmg property.
             * 
             * @return
             *     possible object is
             *     {@link Dmg }
             *     
             */
            public Dmg getDmg() {
                return dmg;
            }

            /**
             * Sets the value of the dmg property.
             * 
             * @param value
             *     allowed object is
             *     {@link Dmg }
             *     
             */
            public void setDmg(Dmg value) {
                this.dmg = value;
            }

            /**
             * Gets the value of the score property.
             * 
             * @return
             *     possible object is
             *     {@link Score }
             *     
             */
            public Score getScore() {
                return score;
            }

            /**
             * Sets the value of the score property.
             * 
             * @param value
             *     allowed object is
             *     {@link Score }
             *     
             */
            public void setScore(Score value) {
                this.score = value;
            }

            /**
             * Gets the value of the farm property.
             * 
             * @return
             *     possible object is
             *     {@link Farm }
             *     
             */
            public Farm getFarm() {
                return farm;
            }

            /**
             * Sets the value of the farm property.
             * 
             * @param value
             *     allowed object is
             *     {@link Farm }
             *     
             */
            public void setFarm(Farm value) {
                this.farm = value;
            }

            /**
             * Gets the value of the wards property.
             * 
             * @return
             *     possible object is
             *     {@link Wards }
             *     
             */
            public Wards getWards() {
                return wards;
            }

            /**
             * Sets the value of the wards property.
             * 
             * @param value
             *     allowed object is
             *     {@link Wards }
             *     
             */
            public void setWards(Wards value) {
                this.wards = value;
            }

            /**
             * Gets the value of the multiKills property.
             * 
             * @return
             *     possible object is
             *     {@link MultiKills }
             *     
             */
            public MultiKills getMultiKills() {
                return multiKills;
            }

            /**
             * Sets the value of the multiKills property.
             * 
             * @param value
             *     allowed object is
             *     {@link MultiKills }
             *     
             */
            public void setMultiKills(MultiKills value) {
                this.multiKills = value;
            }

            /**
             * Gets the value of the firstBlood property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFirstBlood() {
                return firstBlood;
            }

            /**
             * Sets the value of the firstBlood property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFirstBlood(String value) {
                this.firstBlood = value;
            }

            /**
             * Gets the value of the gold property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGold() {
                return gold;
            }

            /**
             * Sets the value of the gold property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGold(String value) {
                this.gold = value;
            }

            /**
             * Gets the value of the turrets property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTurrets() {
                return turrets;
            }

            /**
             * Sets the value of the turrets property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTurrets(String value) {
                this.turrets = value;
            }

            /**
             * Gets the value of the killingSpree property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getKillingSpree() {
                return killingSpree;
            }

            /**
             * Sets the value of the killingSpree property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setKillingSpree(String value) {
                this.killingSpree = value;
            }

            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Dmg {

                @XmlAttribute(name = "total-dmg-absolute", required = true)
                protected String totalDmgAbsolute = "";
                @XmlAttribute(name = "total-dmg-team-relative", required = true)
                protected String totalDmgTeamRelative = "";
                @XmlAttribute(name = "champ-dmg-absolute", required = true)
                protected String champDmgAbsolute = "";
                @XmlAttribute(name = "champ-dmg-team-relative", required = true)
                protected String champDmgTeamRelative = "";

                /**
                 * Gets the value of the totalDmgAbsolute property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTotalDmgAbsolute() {
                    return totalDmgAbsolute;
                }

                /**
                 * Sets the value of the totalDmgAbsolute property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTotalDmgAbsolute(String value) {
                    this.totalDmgAbsolute = value;
                }

                /**
                 * Gets the value of the totalDmgTeamRelative property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTotalDmgTeamRelative() {
                    return totalDmgTeamRelative;
                }

                /**
                 * Sets the value of the totalDmgTeamRelative property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTotalDmgTeamRelative(String value) {
                    this.totalDmgTeamRelative = value;
                }

                /**
                 * Gets the value of the champDmgAbsolute property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getChampDmgAbsolute() {
                    return champDmgAbsolute;
                }

                /**
                 * Sets the value of the champDmgAbsolute property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setChampDmgAbsolute(String value) {
                    this.champDmgAbsolute = value;
                }

                /**
                 * Gets the value of the champDmgTeamRelative property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getChampDmgTeamRelative() {
                    return champDmgTeamRelative;
                }

                /**
                 * Sets the value of the champDmgTeamRelative property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setChampDmgTeamRelative(String value) {
                    this.champDmgTeamRelative = value;
                }

            }


            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Farm {

                @XmlAttribute(name = "farm-absolute", required = true)
                protected String farmAbsolute = "";
                @XmlAttribute(name = "farm-team-relative", required = true)
                protected String farmTeamRelative = "";

                /**
                 * Gets the value of the farmAbsolute property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFarmAbsolute() {
                    return farmAbsolute;
                }

                /**
                 * Sets the value of the farmAbsolute property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFarmAbsolute(String value) {
                    this.farmAbsolute = value;
                }

                /**
                 * Gets the value of the farmTeamRelative property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFarmTeamRelative() {
                    return farmTeamRelative;
                }

                /**
                 * Sets the value of the farmTeamRelative property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFarmTeamRelative(String value) {
                    this.farmTeamRelative = value;
                }

            }



            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class MultiKills {

                @XmlAttribute(name = "double", required = true)
                protected String _double = "";
                @XmlAttribute(name = "triple", required = true)
                protected String triple = "";
                @XmlAttribute(name = "quadra", required = true)
                protected String quadra = "";
                @XmlAttribute(name = "penta", required = true)
                protected String penta = "";

                /**
                 * Gets the value of the double property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDouble() {
                    return _double;
                }

                /**
                 * Sets the value of the double property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDouble(String value) {
                    this._double = value;
                }

                /**
                 * Gets the value of the triple property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTriple() {
                    return triple;
                }

                /**
                 * Sets the value of the triple property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTriple(String value) {
                    this.triple = value;
                }

                /**
                 * Gets the value of the quadra property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getQuadra() {
                    return quadra;
                }

                /**
                 * Sets the value of the quadra property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setQuadra(String value) {
                    this.quadra = value;
                }

                /**
                 * Gets the value of the penta property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPenta() {
                    return penta;
                }

                /**
                 * Sets the value of the penta property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPenta(String value) {
                    this.penta = value;
                }

            }


            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Score {

                @XmlAttribute(name = "kills-absolute", required = true)
                protected String killsAbsolute = "";
                @XmlAttribute(name = "kills-team-relative", required = true)
                protected String killsTeamRelative = "";
                @XmlAttribute(name = "deaths-absolute", required = true)
                protected String deathsAbsolute = "";
                @XmlAttribute(name = "deaths-team-relative", required = true)
                protected String deathsTeamRelative = "";
                @XmlAttribute(name = "assists-absolute", required = true)
                protected String assistsAbsolute = "";
                @XmlAttribute(name = "assists-team-relative", required = true)
                protected String assistsTeamRelative = "";

                /**
                 * Gets the value of the killsAbsolute property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getKillsAbsolute() {
                    return killsAbsolute;
                }

                /**
                 * Sets the value of the killsAbsolute property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setKillsAbsolute(String value) {
                    this.killsAbsolute = value;
                }

                /**
                 * Gets the value of the killsTeamRelative property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getKillsTeamRelative() {
                    return killsTeamRelative;
                }

                /**
                 * Sets the value of the killsTeamRelative property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setKillsTeamRelative(String value) {
                    this.killsTeamRelative = value;
                }

                /**
                 * Gets the value of the deathsAbsolute property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDeathsAbsolute() {
                    return deathsAbsolute;
                }

                /**
                 * Sets the value of the deathsAbsolute property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDeathsAbsolute(String value) {
                    this.deathsAbsolute = value;
                }

                /**
                 * Gets the value of the deathsTeamRelative property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDeathsTeamRelative() {
                    return deathsTeamRelative;
                }

                /**
                 * Sets the value of the deathsTeamRelative property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDeathsTeamRelative(String value) {
                    this.deathsTeamRelative = value;
                }

                /**
                 * Gets the value of the assistsAbsolute property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAssistsAbsolute() {
                    return assistsAbsolute;
                }

                /**
                 * Sets the value of the assistsAbsolute property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAssistsAbsolute(String value) {
                    this.assistsAbsolute = value;
                }

                /**
                 * Gets the value of the assistsTeamRelative property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAssistsTeamRelative() {
                    return assistsTeamRelative;
                }

                /**
                 * Sets the value of the assistsTeamRelative property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAssistsTeamRelative(String value) {
                    this.assistsTeamRelative = value;
                }

            }


            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Wards {

                @XmlAttribute(name = "ward-placed", required = true)
                protected String wardPlaced = "";
                @XmlAttribute(name = "ward-destroyed", required = true)
                protected String wardDestroyed = "";

                /**
                 * Gets the value of the wardPlaced property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getWardPlaced() {
                    return wardPlaced;
                }

                /**
                 * Sets the value of the wardPlaced property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setWardPlaced(String value) {
                    this.wardPlaced = value;
                }

                /**
                 * Gets the value of the wardDestroyed property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getWardDestroyed() {
                    return wardDestroyed;
                }

                /**
                 * Sets the value of the wardDestroyed property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setWardDestroyed(String value) {
                    this.wardDestroyed = value;
                }

            }

        }


        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "teamDiff","rank"
        })
        public static class Result {

            @XmlElement(name = "team-diff", required = true)
            protected TeamDiff teamDiff = new TeamDiff();
            @XmlElement(name = "rank", required = true)
            protected Rank rank = new Rank();
            @XmlAttribute(name = "win", required = true)
            protected String win = "";
            @XmlAttribute(name = "length", required = true)
            protected String length = "";
            @XmlAttribute(name = "first-blood", required = true)
            protected String firstBlood = "";

            /**
             * Gets the value of the teamDiff property.
             * 
             * @return
             *     possible object is
             *     {@link TeamDiff }
             *     
             */
            public TeamDiff getTeamDiff() {
                return teamDiff;
            }

            /**
             * Sets the value of the teamDiff property.
             * 
             * @param value
             *     allowed object is
             *     {@link TeamDiff }
             *     
             */
            public void setTeamDiff(TeamDiff value) {
                this.teamDiff = value;
            }

            /**
             * Gets the value of the win property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getWin() {
                return win;
            }

            /**
             * Sets the value of the win property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setWin(String value) {
                this.win = value;
            }

            /**
             * Gets the value of the rank property.
             * 
             * @return
             *     possible object is
             *     {@link Rank }
             *     
             */
            public Rank getRank() {
                return rank;
            }

            /**
             * Sets the value of the rank property.
             * 
             * @param value
             *     allowed object is
             *     {@link Rank }
             *     
             */
            public void setRank(Rank value) {
                this.rank = value;
            }

            /**
             * Gets the value of the length property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLength() {
                return length;
            }

            /**
             * Sets the value of the length property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLength(String value) {
                this.length = value;
            }

            /**
             * Gets the value of the firstBlood property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFirstBlood() {
                return firstBlood;
            }

            /**
             * Sets the value of the firstBlood property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFirstBlood(String value) {
                this.firstBlood = value;
            }


            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class TeamDiff {

                @XmlAttribute(name = "kills-diff", required = true)
                protected String killsDiff = "";
                @XmlAttribute(name = "farm-diff", required = true)
                protected String farmDiff = "";
                @XmlAttribute(name = "gold-diff", required = true)
                protected String goldDiff = "";
                @XmlAttribute(name = "total-dmg-diff", required = true)
                protected String totalDmgDiff = "";
                @XmlAttribute(name = "champ-dmg-diff", required = true)
                protected String champDmgDiff = "";
                @XmlAttribute(name = "drake-diff", required = true)
                protected String drakeDiff = "";
                @XmlAttribute(name = "nashor-diff", required = true)
                protected String nashorDiff = "";
                @XmlAttribute(name = "turret-diff", required = true)
                protected String turretDiff = "";
                @XmlAttribute(name = "inhibitor-diff", required = true)
                protected String inhibitorDiff = "";

                /**
                 * Gets the value of the killsDiff property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getKillsDiff() {
                    return killsDiff;
                }

                /**
                 * Sets the value of the killsDiff property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setKillsDiff(String value) {
                    this.killsDiff = value;
                }

                /**
                 * Gets the value of the farmDiff property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFarmDiff() {
                    return farmDiff;
                }

                /**
                 * Sets the value of the farmDiff property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFarmDiff(String value) {
                    this.farmDiff = value;
                }

                /**
                 * Gets the value of the goldDiff property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getGoldDiff() {
                    return goldDiff;
                }

                /**
                 * Sets the value of the goldDiff property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setGoldDiff(String value) {
                    this.goldDiff = value;
                }

                /**
                 * Gets the value of the totalDmgDiff property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTotalDmgDiff() {
                    return totalDmgDiff;
                }

                /**
                 * Sets the value of the totalDmgDiff property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTotalDmgDiff(String value) {
                    this.totalDmgDiff = value;
                }

                /**
                 * Gets the value of the champDmgDiff property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getChampDmgDiff() {
                    return champDmgDiff;
                }

                /**
                 * Sets the value of the champDmgDiff property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setChampDmgDiff(String value) {
                    this.champDmgDiff = value;
                }

                /**
                 * Gets the value of the drakeDiff property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDrakeDiff() {
                    return drakeDiff;
                }

                /**
                 * Sets the value of the drakeDiff property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDrakeDiff(String value) {
                    this.drakeDiff = value;
                }

                /**
                 * Gets the value of the nashorDiff property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getNashorDiff() {
                    return nashorDiff;
                }

                /**
                 * Sets the value of the nashorDiff property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setNashorDiff(String value) {
                    this.nashorDiff = value;
                }

                /**
                 * Gets the value of the turretDiff property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTurretDiff() {
                    return turretDiff;
                }

                /**
                 * Sets the value of the turretDiff property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTurretDiff(String value) {
                    this.turretDiff = value;
                }

                /**
                 * Gets the value of the inhibitorDiff property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getInhibitorDiff() {
                    return inhibitorDiff;
                }

                /**
                 * Sets the value of the inhibitorDiff property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setInhibitorDiff(String value) {
                    this.inhibitorDiff = value;
                }

            }

            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Rank {
                @XmlAttribute(name = "tier", required = true)
                protected String tier = "";
                @XmlAttribute(name = "division", required = true)
                protected String division = "";
                @XmlAttribute(name = "lp", required = true)
                protected String lp = "";

                /**
                 * Gets the value of the tier property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getTier() {
                    return tier;
                }

                /**
                 * Sets the value of the tier property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setTier(String value) {
                    this.tier = value;
                }

                /**
                 * Gets the value of the division property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getDivision() {
                    return division;
                }

                /**
                 * Sets the value of the division property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setDivision(String value) {
                    this.division = value;
                }

                /**
                 * Gets the value of the lp property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getLp() {
                    return lp;
                }

                /**
                 * Sets the value of the lp property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setLp(String value) {
                    this.lp = value;
                }
            }

        }

    }

}
