//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.01 at 12:54:03 PM CET 
//


package org.kaleta.lolstats.backend.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for team complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="team">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="win" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="first-blood" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="turrets" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="inhibitors" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="baron" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="dragon" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "team")
public class Team {

    @XmlAttribute(name = "win", required = true)
    protected String win="";
    @XmlAttribute(name = "first-blood", required = true)
    protected String firstBlood="";
    @XmlAttribute(name = "turrets", required = true)
    protected String turrets="";
    @XmlAttribute(name = "inhibitors", required = true)
    protected String inhibitors="";
    @XmlAttribute(name = "baron", required = true)
    protected String baron="";
    @XmlAttribute(name = "dragon", required = true)
    protected String dragon="";

    /**
     * Gets the value of the win property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWin() {
        return win;
    }

    /**
     * Sets the value of the win property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWin(String value) {
        this.win = value;
    }

    /**
     * Gets the value of the firstBlood property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstBlood() {
        return firstBlood;
    }

    /**
     * Sets the value of the firstBlood property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstBlood(String value) {
        this.firstBlood = value;
    }

    /**
     * Gets the value of the turrets property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTurrets() {
        return turrets;
    }

    /**
     * Sets the value of the turrets property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTurrets(String value) {
        this.turrets = value;
    }

    /**
     * Gets the value of the inhibitors property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInhibitors() {
        return inhibitors;
    }

    /**
     * Sets the value of the inhibitors property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInhibitors(String value) {
        this.inhibitors = value;
    }

    /**
     * Gets the value of the baron property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaron() {
        return baron;
    }

    /**
     * Sets the value of the baron property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaron(String value) {
        this.baron = value;
    }

    /**
     * Gets the value of the dragon property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDragon() {
        return dragon;
    }

    /**
     * Sets the value of the dragon property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDragon(String value) {
        this.dragon = value;
    }

}
